name: create-samples
on:
  push:
    branches: [main]

jobs:
  create-samples:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v1
    - run: ./docker.sh build
    - run: ./docker.sh run
      env:
        DEBUG: 1
    - run: ./publish_samples.sh
      env:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
