name: generate
on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v1
    - run: |
        ./docker.sh build
        ./docker.sh run
        ./publish_frameworks.sh
      env:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
