name: generate
on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    container: ./devcontainer/Dockerfile
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v1
    - run: |
        ./init_frameworks.sh
        ./publish_frameworks.sh
      env:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
