name: generate
on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v1
    - run: |
        docker build -t dev - < .devcontainer/Dockerfile
        docker run --rm -v $(pwd):/repo -w /repo dev ./init_frameworks.sh
        ./publish_frameworks.sh
      env:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
